# src/Ens/JobeetBundle/Resources/config/routing.yml
LinForumBundle_post:
    resource: "@LinForumBundle/Resources/config/routing/post.php"
    prefix: /post
    
LinForumBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: LinForumBundle:Default:index }
